<a href="https://colab.research.google.com/github/gunjan7858903606/gunjan/blob/main/Untitled74.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas dataframes

# practice with nba data set for lear informations

In [1]:
import numpy as np
import pandas as pd

In [3]:
df_nba = pd.read_csv("/content/nba (2).csv")

In [ ]:
df_nba.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90,PF,29,06-09,240,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55,PF,21,06-08,235,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41,C,25,7-0,238,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12,PG,22,06-02,190,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36,PG,22,06-04,220,Oklahoma State,3431040.0

In [4]:
type(df_nba)

pandas.core.frame.DataFrame

In [5]:
df_nba.dtypes

Name         object
Team         object
Number        int64
Position     object
Age           int64
Height       object
Weight        int64
College      object
Salary      float64
dtype: object

In [6]:
df_nba.shape

(457, 9)

In [7]:
df_nba.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [8]:
df_nba.isnull()

      Name   Team  Number  Position    Age  Height  Weight  College  Salary
0    False  False   False     False  False   False   False    False   False
1    False  False   False     False  False   False   False    False   False
2    False  False   False     False  False   False   False    False    True
3    False  False   False     False  False   False   False    False   False
4    False  False   False     False  False   False   False     True   False
..     ...    ...     ...       ...    ...     ...     ...      ...     ...
452  False  False   False     False  False   False   False    False   False
453  False  False   False     False  False   False   False    False   False
454  False  False   False     False  False   False   False     True   False
455  False  False   False     False  False   False   False     True   False
456  False  False   False     False  False   False   False    False   False

[457 rows x 9 columns]

In [9]:
df_nba .describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [10]:
df_nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    int64
 3   Position  457 non-null    object
 4   Age       457 non-null    int64
 5   Height    457 non-null    object
 6   Weight    457 non-null    int64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(1), int64(3), object(5)
memory usage: 32.3+ KB

In [11]:
df_nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [12]:
df_nba.index

RangeIndex(start=0, stop=457, step=1)

In [13]:
df_nba.values

array([['Avery Bradley', 'Boston Celtics', 0, ..., 180, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99, ..., 235, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30, ..., 205,
        'Boston University', nan],
       ...,
       ['Raul Neto', 'Utah Jazz', 25, ..., 179, nan, 900000.0],
       ['Tibor Pleiss', 'Utah Jazz', 21, ..., 256, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24, ..., 231, 'Kansas', 947276.0]],
      dtype=object)

In [14]:
df_nba.value_counts

<bound method DataFrame.value_counts of               Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25  06-02     180
1      Jae Crowder  Boston Celtics      99       SF   25  06-06     235
2     John Holland  Boston Celtics      30       SG   27  06-05     205
3      R.J. Hunter  Boston Celtics      28       SG   22  06-05     185
4    Jonas Jerebko  Boston Celtics       8       PF   29  06-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20  06-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26  06-03     203
454      Raul Neto       Utah Jazz      25       PG   24  06-01     179
455   Tibor Pleiss       Utah Jazz      21        C   26  07-03     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]>

In [15]:
df_nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41,PF,20,06-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [16]:
df_nba.sample()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
5,Amir Johnson,Boston Celtics,90,PF,29,06-09,240,NaN,12000000.0

In [17]:
df_nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

# sort values

In [18]:
df_nba.sort_values(by = ["Name"],ascending = False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
237,Zaza Pachulia,Dallas Mavericks,27,C,32,06-11,275,NaN,5200000.0
271,Zach Randolph,Memphis Grizzlies,50,PF,34,06-09,260,Michigan State,9638555.0
402,Zach LaVine,Minnesota Timberwolves,8,PG,21,06-05,189,UCLA,2148360.0
270,Xavier Munford,Memphis Grizzlies,14,PG,24,06-03,180,Rhode Island,NaN
386,Wilson Chandler,Denver Nuggets,21,SF,29,06-08,225,DePaul,10449438.0
...,...,...,...,...,...,...,...,...,...
312,Al Horford,Atlanta Hawks,15,C,30,06-10,245,Florida,12000000.0
404,Adreian Payne,Minnesota Timberwolves,33,PF,25,06-10,237,Michigan State,1938840.0
328,Aaron Harrison,Charlotte Hornets,9,SG,21,06-06,210,Kentucky,525093.0
356,Aaron Gordon,Orlando Magic,0,PF,20,06-09,220,Arizona,4171680.0
152,Aaron Brooks,Chicago Bulls,0,PG,31,6-0,161,Oregon,2250000.0

In [19]:
df_nba.sort_values(by = ["Age"],ascending = True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
226,Rashad Vaughn,Milwaukee Bucks,20,SG,19,06-06,202,UNLV,1733040.0
122,Devin Booker,Phoenix Suns,1,SG,19,06-06,206,Kentucky,2127840.0
40,Kristaps Porzingis,New York Knicks,6,PF,20,07-03,240,NaN,4131720.0
401,Tyus Jones,Minnesota Timberwolves,1,PG,20,06-02,195,Duke,1282080.0
427,Cliff Alexander,Portland Trail Blazers,34,PF,20,06-08,240,Kansas,525093.0
...,...,...,...,...,...,...,...,...,...
261,Vince Carter,Memphis Grizzlies,15,SG,39,06-06,220,North Carolina,4088019.0
102,Pablo Prigioni,Los Angeles Clippers,9,PG,39,06-03,185,NaN,947726.0
298,Tim Duncan,San Antonio Spurs,21,C,40,06-11,250,Wake Forest,5250000.0
400,Kevin Garnett,Minnesota Timberwolves,21,PF,40,06-11,240,NaN,8500000.0
304,Andre Miller,San Antonio Spurs,24,PG,40,06-03,200,Utah,250750.0

In [20]:
df_nba.sort_values(by = ["Salary"],ascending = False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24,SF,37,06-06,212,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,23,SF,31,06-08,250,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,7,SF,32,06-08,240,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12,C,30,06-11,265,NaN,22359364.0
339,Chris Bosh,Miami Heat,1,PF,32,06-11,235,Georgia Tech,22192730.0
...,...,...,...,...,...,...,...,...,...
273,Alex Stepheson,Memphis Grizzlies,35,PF,28,06-10,270,USC,NaN
350,Briante Weber,Miami Heat,12,PG,23,06-02,165,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,11,SF,30,06-09,205,NaN,NaN
397,Axel Toupane,Denver Nuggets,6,SG,23,06-07,210,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4,PF,25,06-10,250,Fresno State,NaN

In [21]:
# sort by Team and Salary
df_nba.sort_values(by = ["Team","Salary"],ascending = True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
317,Lamar Patterson,Atlanta Hawks,13,SG,24,06-05,225,Pittsburgh,525093.0
316,Mike Muscala,Atlanta Hawks,31,PF,24,06-11,240,Bucknell,947276.0
313,Kris Humphries,Atlanta Hawks,43,PF,31,06-09,235,Minnesota,1000000.0
322,Walter Tavares,Atlanta Hawks,22,C,24,07-03,260,NaN,1000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,10,SG,24,06-06,205,Michigan,1304520.0
...,...,...,...,...,...,...,...,...,...
369,Bradley Beal,Washington Wizards,3,SG,22,06-05,207,Florida,5694674.0
376,Markieff Morris,Washington Wizards,5,PF,26,06-10,245,Kansas,8000000.0
373,Marcin Gortat,Washington Wizards,13,C,32,06-11,240,NaN,11217391.0
375,Nene Hilario,Washington Wizards,42,C,33,06-11,250,NaN,13000000.0
382,John Wall,Washington Wizards,2,PG,25,06-04,195,Kentucky,15851950.0

In [23]:
# sort by Team and Salary in desending order
df_nba.sort_values(by = ["Team","Salary"])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
317,Lamar Patterson,Atlanta Hawks,13,SG,24,06-05,225,Pittsburgh,525093.0
316,Mike Muscala,Atlanta Hawks,31,PF,24,06-11,240,Bucknell,947276.0
313,Kris Humphries,Atlanta Hawks,43,PF,31,06-09,235,Minnesota,1000000.0
322,Walter Tavares,Atlanta Hawks,22,C,24,07-03,260,NaN,1000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,10,SG,24,06-06,205,Michigan,1304520.0
...,...,...,...,...,...,...,...,...,...
369,Bradley Beal,Washington Wizards,3,SG,22,06-05,207,Florida,5694674.0
376,Markieff Morris,Washington Wizards,5,PF,26,06-10,245,Kansas,8000000.0
373,Marcin Gortat,Washington Wizards,13,C,32,06-11,240,NaN,11217391.0
375,Nene Hilario,Washington Wizards,42,C,33,06-11,250,NaN,13000000.0
382,John Wall,Washington Wizards,2,PG,25,06-04,195,Kentucky,15851950.0

# values countes

In [24]:
df_nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [25]:
df_nba.Position.value_counts()

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

In [26]:
df_nba["Position"].value_counts()

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

In [28]:
df_nba.Team.value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Charlotte Hornets         15
Atlanta Hawks             15
San Antonio Spurs         15
Houston Rockets           15
Dallas Mavericks          15
Indiana Pacers            15
Detroit Pistons           15
Cleveland Cavaliers       15
Chicago Bulls             15
Sacramento Kings          15
Phoenix Suns              15
Los Angeles Lakers        15
Los Angeles Clippers      15
Golden State Warriors     15
Toronto Raptors           15
Philadelphia 76ers        15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [30]:
df_nba[["College","Team"]].value_counts()

College         Team
Kentucky        Phoenix Suns              4
North Carolina  Memphis Grizzlies         3
Duke            Miami Heat                3
UCLA            Memphis Grizzlies         3
Kentucky        Sacramento Kings          3
                                         ..
Kansas          Philadelphia 76ers        1
                Oklahoma City Thunder     1
                Minnesota Timberwolves    1
                Los Angeles Lakers        1
Xavier          San Antonio Spurs         1
Name: count, Length: 336, dtype: int64

In [31]:
df_nba[["College", "Team","Salary"]].value_counts()

College         Team                  Salary
Kentucky        Phoenix Suns          13500000.0    2
Alabama         Cleveland Cavaliers   2100000.0     1
Oklahoma State  Memphis Grizzlies     5158539.0     1
Pittsburgh      Atlanta Hawks         525093.0      1
Penn State      New Orleans Pelicans  845059.0      1
                                                   ..
Kansas          Cleveland Cavaliers   1276000.0     1
                Brooklyn Nets         981348.0      1
                Atlanta Hawks         2854940.0     1
Iowa State      New Orleans Pelicans  169883.0      1
Xavier          San Antonio Spurs     1499187.0     1
Name: count, Length: 363, dtype: int64

In [32]:
df_nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [34]:
df_nba["Name"].unique()

array(['Avery Bradley', 'Jae Crowder', 'John Holland', 'R.J. Hunter',
       'Jonas Jerebko', 'Amir Johnson', 'Jordan Mickey', 'Kelly Olynyk',
       'Terry Rozier', 'Marcus Smart', 'Jared Sullinger', 'Isaiah Thomas',
       'Evan Turner', 'James Young', 'Tyler Zeller', 'Bojan Bogdanovic',
       'Markel Brown', 'Wayne Ellington', 'Rondae Hollis-Jefferson',
       'Jarrett Jack', 'Sergey Karasev', 'Sean Kilpatrick',
       'Shane Larkin', 'Brook Lopez', 'Chris McCullough', 'Willie Reed',
       'Thomas Robinson', 'Henry Sims', 'Donald Sloan', 'Thaddeus Young',
       'Arron Afflalo', 'Lou Amundson', 'Thanasis Antetokounmpo',
       'Carmelo Anthony', 'Jose Calderon', 'Cleanthony Early',
       'Langston Galloway', 'Jerian Grant', 'Robin Lopez', "Kyle O'Quinn",
       'Kristaps Porzingis', 'Kevin Seraphin', 'Lance Thomas',
       'Sasha Vujacic', 'Derrick Williams', 'Tony Wroten', 'Elton Brand',
       'Isaiah Canaan', 'Robert Covington', 'Joel Embiid', 'Jerami Grant',
       'Richaun Holmes', 'Carl Landry', 'Kendall Marshall',
       'T.J. McConnell', 'Nerlens Noel', 'Jahlil Okafor', 'Ish Smith',
       'Nik Stauskas', 'Hollis Thompson', 'Christian Wood',
       'Bismack Biyombo', 'Bruno Caboclo', 'DeMarre Carroll',
       'DeMar DeRozan', 'James Johnson', 'Cory Joseph', 'Kyle Lowry',
       'Lucas Nogueira', 'Patrick Patterson', 'Norman Powell',
       'Terrence Ross', 'Luis Scola', 'Jason Thompson',
       'Jonas Valanciunas', 'Delon Wright', 'Leandro Barbosa',
       'Harrison Barnes', 'Andrew Bogut', 'Ian Clark', 'Stephen Curry',
       'Festus Ezeli', 'Draymond Green', 'Andre Iguodala',
       'Shaun Livingston', 'Kevon Looney', 'James Michael McAdoo',
       'Brandon Rush', 'Marreese Speights', 'Klay Thompson',
       'Anderson Varejao', 'Cole Aldrich', 'Jeff Ayres', 'Jamal Crawford',
       'Branden Dawson', 'Jeff Green', 'Blake Griffin', 'Wesley Johnson',
       'DeAndre Jordan', 'Luc Richard Mbah a Moute', 'Chris Paul',
       'Paul Pierce', 'Pablo Prigioni', 'JJ Redick', 'Austin Rivers',
       'C.J. Wilcox', 'Brandon Bass', 'Tarik Black', 'Anthony Brown',
       'Kobe Bryant', 'Jordan Clarkson', 'Roy Hibbert', 'Marcelo Huertas',
       'Ryan Kelly', 'Larry Nance Jr.', 'Julius Randle',
       "D'Angelo Russell", 'Robert Sacre', 'Louis Williams',
       'Metta World Peace', 'Nick Young', 'Eric Bledsoe', 'Devin Booker',
       'Chase Budinger', 'Tyson Chandler', 'Archie Goodwin',
       'John Jenkins', 'Brandon Knight', 'Alex Len', 'Jon Leuer',
       'Phil Pressey', 'Ronnie Price', 'Mirza Teletovic', 'P.J. Tucker',
       'T.J. Warren', 'Alan Williams', 'Quincy Acy', 'James Anderson',
       'Marco Belinelli', 'Caron Butler', 'Omri Casspi',
       'Willie Cauley-Stein', 'Darren Collison', 'DeMarcus Cousins',
       'Seth Curry', 'Duje Dukan', 'Rudy Gay', 'Kosta Koufos',
       'Ben McLemore', 'Eric Moreland', 'Rajon Rondo', 'Cameron Bairstow',
       'Aaron Brooks', 'Jimmy Butler', 'Mike Dunleavy',
       'Cristiano Felicio', 'Pau Gasol', 'Taj Gibson', 'Justin Holiday',
       'Doug McDermott', 'Nikola Mirotic', "E'Twaun Moore", 'Joakim Noah',
       'Bobby Portis', 'Derrick Rose', 'Tony Snell',
       'Matthew Dellavedova', 'Channing Frye', 'Kyrie Irving',
       'LeBron James', 'Richard Jefferson', 'Dahntay Jones',
       'James Jones', 'Sasha Kaun', 'Kevin Love', 'Jordan McRae',
       'Timofey Mozgov', 'Iman Shumpert', 'J.R. Smith',
       'Tristan Thompson', 'Mo Williams', 'Joel Anthony', 'Aron Baynes',
       'Steve Blake', 'Lorenzo Brown', 'Reggie Bullock',
       'Kentavious Caldwell-Pope', 'Spencer Dinwiddie', 'Andre Drummond',
       'Tobias Harris', 'Darrun Hilliard', 'Reggie Jackson',
       'Stanley Johnson', 'Jodie Meeks', 'Marcus Morris',
       'Anthony Tolliver', 'Lavoy Allen', 'Rakeem Christmas',
       'Monta Ellis', 'Paul George', 'George Hill', 'Jordan Hill',
       'Solomon Hill', 'Ty Lawson', 'Ian Mahinmi', 'C.J. Miles',
       'Glenn Robinson III', 'Rodney Stuckey', 'Myles Turner',
       'Shayne Whittington', 'Joe Young', 'Giannis Antetokounmpo',
       'Jerryd Bayless', 'Michael Carter-Williams', 'Jared Cunningham',
       'Tyler Ennis', 'John Henson', 'Damien Inglis', 'O.J. Mayo',
       'Khris Middleton', 'Greg Monroe', 'Steve Novak',
       "Johnny O'Bryant III", 'Jabari Parker', 'Miles Plumlee',
       'Greivis Vasquez', 'Rashad Vaughn', 'Justin Anderson',
       'J.J. Barea', 'Jeremy Evans', 'Raymond Felton', 'Devin Harris',
       'David Lee', 'Wesley Matthews', 'JaVale McGee', 'Salah Mejri',
       'Dirk Nowitzki', 'Zaza Pachulia', 'Chandler Parsons',
       'Dwight Powell', 'Charlie Villanueva', 'Deron Williams',
       'Trevor Ariza', 'Michael Beasley', 'Patrick Beverley',
       'Corey Brewer', 'Clint Capela', 'Sam Dekker', 'Andrew Goudelock',
       'James Harden', 'Montrezl Harrell', 'Dwight Howard',
       'Terrence Jones', 'K.J. McDaniels', 'Donatas Motiejunas',
       'Josh Smith', 'Jason Terry', 'Jordan Adams', 'Tony Allen',
       'Chris Andersen', 'Matt Barnes', 'Vince Carter', 'Mike Conley',
       'Bryce Cotton', 'Jordan Farmar', 'Marc Gasol', 'JaMychal Green',
       'P.J. Hairston', 'Jarell Martin', 'Ray McCallum', 'Xavier Munford',
       'Zach Randolph', 'Lance Stephenson', 'Alex Stepheson',
       'Brandan Wright', 'Alexis Ajinca', 'Ryan Anderson', 'Omer Asik',
       'Luke Babbitt', 'Norris Cole', 'Dante Cunningham', 'Anthony Davis',
       'Bryce Dejean-Jones', 'Toney Douglas', 'James Ennis',
       'Tyreke Evans', 'Tim Frazier', 'Alonzo Gee', 'Eric Gordon',
       'Jordan Hamilton', 'Jrue Holiday', 'Orlando Johnson',
       'Kendrick Perkins', 'Quincy Pondexter', 'LaMarcus Aldridge',
       'Kyle Anderson', 'Matt Bonner', 'Boris Diaw', 'Tim Duncan',
       'Manu Ginobili', 'Danny Green', 'Kawhi Leonard',
       'Boban Marjanovic', 'Kevin Martin', 'Andre Miller', 'Patty Mills',
       'Tony Parker', 'Jonathon Simmons', 'David West', 'Kent Bazemore',
       'Tim Hardaway Jr.', 'Kirk Hinrich', 'Al Horford', 'Kris Humphries',
       'Kyle Korver', 'Paul Millsap', 'Mike Muscala', 'Lamar Patterson',
       'Dennis Schroder', 'Mike Scott', 'Thabo Sefolosha',
       'Tiago Splitter', 'Walter Tavares', 'Jeff Teague', 'Nicolas Batum',
       'Troy Daniels', 'Jorge Gutierrez', 'Tyler Hansbrough',
       'Aaron Harrison', 'Spencer Hawes', 'Al Jefferson',
       'Frank Kaminsky III', 'Michael Kidd-Gilchrist', 'Jeremy Lamb',
       'Courtney Lee', 'Jeremy Lin', 'Kemba Walker', 'Marvin Williams',
       'Cody Zeller', 'Chris Bosh', 'Luol Deng', 'Goran Dragic',
       'Gerald Green', 'Udonis Haslem', 'Joe Johnson', 'Tyler Johnson',
       'Josh McRoberts', 'Josh Richardson', "Amar'e Stoudemire",
       'Dwyane Wade', 'Briante Weber', 'Hassan Whiteside',
       'Justise Winslow', 'Dorell Wright', 'Dewayne Dedmon',
       'Evan Fournier', 'Aaron Gordon', 'Mario Hezonja', 'Ersan Ilyasova',
       'Brandon Jennings', 'Devyn Marble', 'Shabazz Napier',
       'Andrew Nicholson', 'Victor Oladipo', 'Elfrid Payton',
       'Jason Smith', 'Nikola Vucevic', 'C.J. Watson', 'Alan Anderson',
       'Bradley Beal', 'Jared Dudley', 'Jarell Eddie', 'Drew Gooden',
       'Marcin Gortat', 'JJ Hickson', 'Nene Hilario', 'Markieff Morris',
       'Kelly Oubre Jr.', 'Otto Porter Jr.', 'Ramon Sessions',
       'Garrett Temple', 'Marcus Thornton', 'John Wall', 'Darrell Arthur',
       'D.J. Augustin', 'Will Barton', 'Wilson Chandler',
       'Kenneth Faried', 'Danilo Gallinari', 'Gary Harris',
       'Nikola Jokic', 'Joffrey Lauvergne', 'Mike Miller',
       'Emmanuel Mudiay', 'Jameer Nelson', 'Jusuf Nurkic',
       'JaKarr Sampson', 'Axel Toupane', 'Nemanja Bjelica',
       'Gorgui Dieng', 'Kevin Garnett', 'Tyus Jones', 'Zach LaVine',
       'Shabazz Muhammad', 'Adreian Payne', 'Nikola Pekovic',
       'Tayshaun Prince', 'Ricky Rubio', 'Damjan Rudez', 'Greg Smith',
       'Karl-Anthony Towns', 'Andrew Wiggins', 'Steven Adams',
       'Nick Collison', 'Kevin Durant', 'Randy Foye', 'Josh Huestis',
       'Serge Ibaka', 'Enes Kanter', 'Mitch McGary', 'Nazr Mohammed',
       'Anthony Morrow', 'Cameron Payne', 'Andre Roberson',
       'Kyle Singler', 'Dion Waiters', 'Russell Westbrook',
       'Cliff Alexander', 'Al-Farouq Aminu', 'Pat Connaughton',
       'Allen Crabbe', 'Ed Davis', 'Maurice Harkless', 'Gerald Henderson',
       'Chris Kaman', 'Meyers Leonard', 'Damian Lillard', 'C.J. McCollum',
       'Luis Montero', 'Mason Plumlee', 'Brian Roberts', 'Noah Vonleh',
       'Trevor Booker', 'Trey Burke', 'Alec Burks', 'Dante Exum',
       'Derrick Favors', 'Rudy Gobert', 'Gordon Hayward', 'Rodney Hood',
       'Joe Ingles', 'Chris Johnson', 'Trey Lyles', 'Shelvin Mack',
       'Raul Neto', 'Tibor Pleiss', 'Jeff Withey'], dtype=object)

In [35]:
df_nba["Name"].nunique()

457

In [38]:
df_nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [39]:
df_nba[df_nba.Team == "Boston Celtics"]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90,PF,29,06-09,240,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55,PF,21,06-08,235,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41,C,25,7-0,238,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12,PG,22,06-02,190,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36,PG,22,06-04,220,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7,C,24,06-09,260,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4,PG,27,05-09,185,Washington,6912869.0
12,Evan Turner,Boston Celtics,11,SG,27,06-07,220,Ohio State,3425510.0
13,James Young,Boston Celtics,13,SG,20,06-06,215,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44,C,26,7-0,253,North Carolina,2616975.0

In [41]:
df_nba[df_nba.Name == "Avery Bradley"]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0

In [42]:
team_comb = df_nba.value_counts(["Team","College"]).reset_index()
team_comb[:50]

                      Team              College  count
0             Phoenix Suns             Kentucky      4
1        Memphis Grizzlies       North Carolina      3
2               Miami Heat                 Duke      3
3         Sacramento Kings             Kentucky      3
4       Washington Wizards               Kansas      3
5        Memphis Grizzlies                 UCLA      3
6       Philadelphia 76ers                 Duke      2
7   Minnesota Timberwolves             Kentucky      2
8   Minnesota Timberwolves                 UCLA      2
9    Oklahoma City Thunder             Kentucky      2
10       Charlotte Hornets          Connecticut      2
11       Charlotte Hornets             Kentucky      2
12       Charlotte Hornets       North Carolina      2
13          Indiana Pacers              Arizona      2
14  Portland Trail Blazers                 Duke      2
15        Dallas Mavericks              Florida      2
16    Los Angeles Clippers               Kansas      2
17    Los Angeles Clippers                 Duke      2
18           Chicago Bulls           New Mexico      2
19        Sacramento Kings          Connecticut      2
20     Cleveland Cavaliers              Arizona      2
21           Brooklyn Nets         Georgia Tech      2
22     Cleveland Cavaliers                 Duke      2
23   Golden State Warriors       North Carolina      2
24           Orlando Magic                  USC      2
25               Utah Jazz               Butler      2
26          Boston Celtics           Ohio State      2
27      Washington Wizards                  LSU      2
28         Milwaukee Bucks                 Duke      2
29         Milwaukee Bucks             Syracuse      2
30         New York Knicks             Syracuse      1
31           Orlando Magic                 Iowa      1
32         New York Knicks                 UNLV      1
33           Orlando Magic  Louisiana-Lafayette      1
34         New York Knicks                 UCLA      1
35   Oklahoma City Thunder                 UCLA      1
36           Orlando Magic      St. Bonaventure      1
37         New York Knicks           Washington      1
38         New York Knicks             Stanford      1
39         New York Knicks       Saint Joseph's      1
40           Orlando Magic            Tennessee      1
41         New York Knicks           Notre Dame      1
42           Orlando Magic              Indiana      1
43           Orlando Magic          Connecticut      1
44         New York Knicks        Wichita State      1
45   Oklahoma City Thunder                Texas      1
46           Orlando Magic       Colorado State      1
47           Orlando Magic              Arizona      1
48   Oklahoma City Thunder             Colorado      1
49   Oklahoma City Thunder                 Duke      1

In [43]:
df_nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [44]:
df_nba["Team"] == "Boston Celtics"

0       True
1       True
2       True
3       True
4       True
       ...
452    False
453    False
454    False
455    False
456    False
Name: Team, Length: 457, dtype: bool

In [45]:
df_nba[(df_nba["Age"] >=24) & (df_nba["Age"] <=26)]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
7,Kelly Olynyk,Boston Celtics,41,C,25,7-0,238,Gonzaga,2165160.0
10,Jared Sullinger,Boston Celtics,7,C,24,06-09,260,Ohio State,2569260.0
14,Tyler Zeller,Boston Celtics,44,C,26,7-0,253,North Carolina,2616975.0
...,...,...,...,...,...,...,...,...,...
451,Chris Johnson,Utah Jazz,23,SF,26,06-06,206,Dayton,981348.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

# inplace

In [46]:
temp_df = df_nba.copy()
temp_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [49]:
temp_df.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [52]:
temp_df["College"].fillna(value = "sityog", inplace = True)

In [53]:
temp_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-02,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-06,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-05,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-05,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-10,231,Missing,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-03,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-01,179,Missing,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-03,256,Missing,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [54]:
temp_df.College.isnull().sum()

0

In [55]:
df_nba.groupby("College")["Age"].min()

College
Alabama             25
Arizona             20
Arizona State       26
Arkansas            21
Baylor              25
                    ..
Western Michigan    25
Wichita State       25
Wisconsin           22
Wyoming             23
Xavier              35
Name: Age, Length: 118, dtype: int64